#Getting Started with Data Analysis

In [75]:
import pandas as pd

In [118]:
df = pd.read_csv(r'stack-overflow-developer-survey-2024\survey_results_public.csv',index_col='ResponseId')
schema_df = pd.read_csv("stack-overflow-developer-survey-2024/survey_results_schema.csv", index_col='qname')

In [77]:
pd.set_option("display.max_columns",114)
pd.set_option("display.max_rows",114)

In [145]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [79]:
df.shape

(65437, 114)

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), str(100)
memory usage: 56.9 MB

In [119]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
CodingActivities,QID297,Which of the following best describes the code...,False,MC,MAVR
EdLevel,QID25,Which of the following best describes the high...,True,MC,SAVR
LearnCode,QID276,How do you learn to code? Select all that apply.,False,MC,MAVR
LearnCodeOnline,QID281,What online resources do you use to learn to c...,False,MC,MAVR
TechDoc,QID331,What is the source of the technical documentat...,False,MC,MAVR
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
DevType,QID31,Which of the following describes your current ...,False,MC,SAVR
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,SAVR
PurchaseInfluence,QID278,"What level of influence do you, personally, ha...",False,MC,SAVR
BuyNewTool,QID279,"When buying a new tool or software, how do you...",False,MC,MAVR
BuildvsBuy,QID330,When asked to provide a recommendation for sol...,False,MC,SAVR
TechEndorse,QID335,What product feature do you care about most wh...,False,MC,MAVR
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,DL
CompTotal,QID51,What is your current total <b>annual</b> compe...,False,TE,SL
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
Embedded,QID340,Which <b>embedded systems and technologies</b>...,False,Matrix,Likert
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
ToolsTech,QID275,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
OpSys,QID71,What is the primary <b>operating system</b> in...,False,Matrix,Likert
OfficeStackAsync,QID282,Which <b>collaborative work management and/or ...,False,Matrix,Likert
OfficeStackSync,QID307,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
AISearchDev,QID327,Which <b>AI-powered search and developer tools...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,True,MC,MAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,SAVR
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,SAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,SAVR
SOHow,QID334,How do you use Stack Overflow? Select all tha...,False,MC,MAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,SAVR
AISelect,QID314,Do you currently use AI tools in your developm...,True,MC,SAVR
AISent,QID315,How favorable is your stance on using AI tools...,False,MC,SAVR
AIBen,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIAcc,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR
AIComplex,QID343,How well do the AI tools you use in your devel...,False,MC,SAVR
AITool,QID319,Which parts of your development workflow are y...,False,Matrix,Likert
AINext,QID320,Thinking about how your job and process change...,False,Matrix,Likert
AIThreat,QID338,Do you believe AI is a threat to your current ...,False,MC,SAVR
AIEthics,QID339,Which AI ethical responsibilities are most imp...,False,MC,MAVR
AIChallenges,QID346,What are the challenges to your company/whole ...,False,MC,MAVR
TBranch,QID299,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
ICorPM,QID287,Are you an individual contributor or people ma...,False,MC,SAVR
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
Knowledge,QID289,Please rate your level of agreement with the f...,False,Matrix,Likert
Frequency,QID290,How frequently do you experience each of the f...,False,Matrix,Likert
TimeSearching,QID291,"On an average day, how much time do you typica...",False,MC,SAVR
TimeAnswering,QID292,"On an average day, how much time do you typica...",False,MC,SAVR
Frustration,QID342,Which of these company challenges causes you t...,False,MC,MAVR
ProfessionalTech,QID304,My company has:,False,MC,MAVR
ProfessionalCloud,QID332,"At my company, our applications, databases and...",False,MC,SAVR
ProfessionalQuestion,QID333,"When you have a technical question at work, wh...",False,MC,SAVR
Industry,QID326,What industry is the company you work for in?,False,MC,SAVR
JobSat,QID336,How satisfied are you in your current professi...,False,MC,NPS
JobSatPoints,QID337,Assign points to the following attributes of y...,False,CS,VRTL
SOTeamsUsage,QID286,Does your team use Stack Overflow for Teams?,False,MC,SAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
Knowledge_1,QID289,I have interactions with people outside of my ...,NaN,MC,MAVR
Knowledge_2,QID289,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
Knowledge_3,QID289,I can find up-to-date information within my or...,NaN,MC,MAVR
Knowledge_4,QID289,I am able to quickly find answers to my questi...,NaN,MC,MAVR
Knowledge_5,QID289,I know which system or resource to use to find...,NaN,MC,MAVR
Knowledge_6,QID289,I often find myself answering questions that I...,NaN,MC,MAVR
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
Knowledge_9,QID289,I have asked my employer to reimburse me for t...,NaN,MC,MAVR
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
JobSatPoints_1,QID337,Driving strategy for my team,NaN,MC,MAVR
JobSatPoints_4,QID337,Contributing to open source,NaN,MC,MAVR
JobSatPoints_5,QID337,Securing data and environments,NaN,MC,MAVR
JobSatPoints_6,QID337,Improving quality of code and developer enviro...,NaN,MC,MAVR
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

#DataFrame and Series Basics

#Making a demo DataFrame for practice

In [82]:
people = {
    "first" : ['Corey', 'Jane', 'John'],
    "last" : ['Schafer' , 'Doe', 'Doe'],
    "email" : ['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@email.com']
}

In [83]:
df_people = pd.DataFrame(people)

In [84]:
df_people

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [85]:
df_people['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
2          JohnDoe@email.com
Name: email, dtype: str

In [86]:
type(df_people)

pandas.DataFrame

In [87]:
type(df_people['email'])

pandas.Series

In [88]:
df_people[['last','email']]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@gmail.com
2      Doe        JohnDoe@email.com

In [89]:
type(df_people[['last','email']])

pandas.DataFrame

In [90]:
df_people.iloc[0]

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [91]:
df_people.iloc[[0,1]]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com

In [92]:
df_people.iloc[[0,1], [0,1]]

   first     last
0  Corey  Schafer
1   Jane      Doe

In [93]:
df_people.loc[[0,1],['email','last']]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@gmail.com      Doe

#Working with the main DataFrame

In [94]:
df.shape

(65437, 114)

In [95]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=114)

In [96]:
df['Age']

0        Under 18 years old
1           35-44 years old
2           45-54 years old
3           18-24 years old
4           18-24 years old
                ...
65432       18-24 years old
65433       25-34 years old
65434       25-34 years old
65435       18-24 years old
65436       18-24 years old
Name: Age, Length: 65437, dtype: str

In [97]:
df['Age'].value_counts()

Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64

In [98]:
df.loc[0:5,['Age','Employment']]

                  Age           Employment
0  Under 18 years old  Employed, full-time
1     35-44 years old  Employed, full-time
2     45-54 years old  Employed, full-time
3     18-24 years old   Student, full-time
4     18-24 years old   Student, full-time
5  Under 18 years old   Student, full-time

In [99]:
# Indexes

In [100]:
df_people.set_index('email')

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@gmail.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [ ]:
df_people

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [102]:
df_people.set_index('email', inplace=True)

In [103]:
df_people

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@gmail.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [104]:
df_people.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@email.com'], dtype='str', name='email')

In [105]:
df_people.loc['CoreyMSchafer@gmail.com']

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [108]:
df_people.reset_index(inplace=True)
df_people

   level_0  index                    email  first     last
0        0      0  CoreyMSchafer@gmail.com  Corey  Schafer
1        1      1        JaneDoe@gmail.com   Jane      Doe
2        2      2        JohnDoe@email.com   John      Doe

#Did index_col='ResponseId' and index_col='qname' in the start

In [121]:
schema_df.sort_index()

,qid,question,force_resp,type,selector
qname,,,,,
AIAcc,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR
AIBen,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIChallenges,QID346,What are the challenges to your company/whole ...,False,MC,MAVR
AIComplex,QID343,How well do the AI tools you use in your devel...,False,MC,SAVR
AIEthics,QID339,Which AI ethical responsibilities are most imp...,False,MC,MAVR
AINext,QID320,Thinking about how your job and process change...,False,Matrix,Likert
AISearchDev,QID327,Which <b>AI-powered search and developer tools...,False,Matrix,Likert
AISelect,QID314,Do you currently use AI tools in your developm...,True,MC,SAVR
AISent,QID315,How favorable is your stance on using AI tools...,False,MC,SAVR
AIThreat,QID338,Do you believe AI is a threat to your current ...,False,MC,SAVR
AITool,QID319,Which parts of your development workflow are y...,False,Matrix,Likert
Age,QID127,What is your age?*,True,MC,SAVR
BuildvsBuy,QID330,When asked to provide a recommendation for sol...,False,MC,SAVR
BuyNewTool,QID279,"When buying a new tool or software, how do you...",False,MC,MAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
CodingActivities,QID297,Which of the following best describes the code...,False,MC,MAVR
CompTotal,QID51,What is your current total <b>annual</b> compe...,False,TE,SL
Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,DL
Database,QID262,Which <b>database environments </b>have you do...,False,Matrix,Likert
DevType,QID31,Which of the following describes your current ...,False,MC,SAVR
EdLevel,QID25,Which of the following best describes the high...,True,MC,SAVR
Embedded,QID340,Which <b>embedded systems and technologies</b>...,False,Matrix,Likert
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
Frequency,QID290,How frequently do you experience each of the f...,False,Matrix,Likert
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
Frustration,QID342,Which of these company challenges causes you t...,False,MC,MAVR
ICorPM,QID287,Are you an individual contributor or people ma...,False,MC,SAVR
Industry,QID326,What industry is the company you work for in?,False,MC,SAVR
JobSat,QID336,How satisfied are you in your current professi...,False,MC,NPS
JobSatPoints,QID337,Assign points to the following attributes of y...,False,CS,VRTL
JobSatPoints_1,QID337,Driving strategy for my team,NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR
JobSatPoints_4,QID337,Contributing to open source,NaN,MC,MAVR
JobSatPoints_5,QID337,Securing data and environments,NaN,MC,MAVR
JobSatPoints_6,QID337,Improving quality of code and developer enviro...,NaN,MC,MAVR
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
Knowledge,QID289,Please rate your level of agreement with the f...,False,Matrix,Likert
Knowledge_1,QID289,I have interactions with people outside of my ...,NaN,MC,MAVR
Knowledge_2,QID289,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
Knowledge_3,QID289,I can find up-to-date information within my or...,NaN,MC,MAVR
Knowledge_4,QID289,I am able to quickly find answers to my questi...,NaN,MC,MAVR
Knowledge_5,QID289,I know which system or resource to use to find...,NaN,MC,MAVR
Knowledge_6,QID289,I often find myself answering questions that I...,NaN,MC,MAVR
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
Knowledge_9,QID289,I have asked my employer to reimburse me for t...,NaN,MC,MAVR
Language,QID233,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
LearnCode,QID276,How do you learn to code? Select all that apply.,False,MC,MAVR
LearnCodeOnline,QID281,What online resources do you use to learn to c...,False,MC,MAVR
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
MiscTech,QID265,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
NEWCollabTools,QID274,Which <strong>development environments</strong...,False,Matrix,Likert
NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,True,MC,MAVR
OfficeStackAsync,QID282,Which <b>collaborative work management and/or ...,False,Matrix,Likert
OfficeStackSync,QID307,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
OpSys,QID71,What is the primary <b>operating system</b> in...,False,Matrix,Likert
OrgSize,QID29,Approximately how many people are employed by ...,False,MC,SAVR
Platform,QID263,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
ProfessionalCloud,QID332,"At my company, our applications, databases and...",False,MC,SAVR
ProfessionalQuestion,QID333,"When you have a technical question at work, wh...",False,MC,SAVR
ProfessionalTech,QID304,My company has:,False,MC,MAVR
PurchaseInfluence,QID278,"What level of influence do you, personally, ha...",False,MC,SAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
SOAccount,QID101,Do you have a Stack Overflow account?,False,MC,SAVR
SOComm,QID106,Do you consider yourself a member of the Stack...,False,MC,SAVR
SOHow,QID334,How do you use Stack Overflow? Select all tha...,False,MC,MAVR
SOPartFreq,QID102,How frequently would you say you participate i...,False,MC,SAVR
SOTeamsUsage,QID286,Does your team use Stack Overflow for Teams?,False,MC,SAVR
SOVisitFreq,QID100,How frequently would you say you visit Stack O...,False,MC,SAVR
SurveyEase,QID133,How easy or difficult was this survey to compl...,False,MC,MAVR
SurveyLength,QID132,How do you feel about the length of the survey...,False,MC,MAVR
TBranch,QID299,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
TechDoc,QID331,What is the source of the technical documentat...,False,MC,MAVR
TechEndorse,QID335,What product feature do you care about most wh...,False,MC,MAVR
TimeAnswering,QID292,"On an average day, how much time do you typica...",False,MC,SAVR
TimeSearching,QID291,"On an average day, how much time do you typica...",False,MC,SAVR
ToolsTech,QID275,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

#Filtering - Using Conditionals to Filter Rows and Columns

In [123]:
df_people

   level_0  index                    email  first     last
0        0      0  CoreyMSchafer@gmail.com  Corey  Schafer
1        1      1        JaneDoe@gmail.com   Jane      Doe
2        2      2        JohnDoe@email.com   John      Doe

In [122]:
df_people['last'] == 'Doe'

0    False
1     True
2     True
Name: last, dtype: bool

In [126]:
filt = (df_people['last'] == 'Doe')
df_people[filt]

   level_0  index              email first last
1        1      1  JaneDoe@gmail.com  Jane  Doe
2        2      2  JohnDoe@email.com  John  Doe

#using filt as filter filter is a keyword in python

In [128]:
df_people[df_people['last'] == 'Doe']

   level_0  index              email first last
1        1      1  JaneDoe@gmail.com  Jane  Doe
2        2      2  JohnDoe@email.com  John  Doe

In [129]:
df_people.loc[filt,'email']

1    JaneDoe@gmail.com
2    JohnDoe@email.com
Name: email, dtype: str

In [133]:
filt = (df_people['first'] == 'John') & (df_people['last'] == 'Doe')
df_people.loc[filt]

   level_0  index              email first last
2        2      2  JohnDoe@email.com  John  Doe

In [134]:
filt = (df_people['first'] == 'John') | (df_people['last'] == 'Schafer')
df_people.loc[filt]

   level_0  index                    email  first     last
0        0      0  CoreyMSchafer@gmail.com  Corey  Schafer
2        2      2        JohnDoe@email.com   John      Doe

In [135]:
df_people.loc[~filt]

   level_0  index              email first last
1        1      1  JaneDoe@gmail.com  Jane  Doe

#YearsCode is a string

In [146]:
high_exp = (df['YearsCode'] == '20')
df[high_exp]

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,NaN,20,NaN,Academic researcher,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Lua,Lua,Lua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,NaN,NaN,NaN,Skype,Skype,Skype,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Engage with community by commenting on questio...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,NaN,Project manager,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,JavaScript;Python;Ruby,C#;Crystal;Java;JavaScript;Python;Ruby,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Google Cloud,Google Cloud,Node.js;React;Ruby on Rails,Django;Node.js;React;Ruby on Rails,Node.js;React;Ruby on Rails,NaN,NaN,NaN,NaN,NaN,NaN,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows,Confluence;GitHub Discussions;Jira;Smartsheet,Confluence;GitHub Discussions;Jira,Confluence;GitHub Discussions;Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,ChatGPT;GitHub Copilot;Google Gemini;Meta AI;V...,GitHub Copilot;Google Gemini;Visual Studio Int...,GitHub Copilot;Google Gemini;Visual Studio Int...,Stack Overflow for Teams (private knowledge sh...,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Testing code;Generating conte...,Committing and reviewing code;Deployment and m...,NaN,NaN,Learning about a codebase;Writing code;Documen...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,15.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,3-5 times a week,6-10 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),Internal Developer portal,Healthcare,50.0,0.0,0.0,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
13,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Sch...,NaN,NaN,20,12,"Developer, back-end",NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);C#;JavaScript;PowerShe...,Bash/Shell (all shells);JavaScript;VBA,Bash/Shell (all shells);JavaScript;VBA,MySQL,MySQL,MySQL,Amazon Web Services (AWS);Google Cloud;Hetzner...,Hetzner;VMware,Hetzner;VMware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ansible;Chocolatey;Docker;Make;NuGet;Pacman;Pi...,Ansible;Docker;Pacman,Ansible;Docker;Pacman,Notepad++;Vim;Visual Studio Code,Neovim;Notepad++;Vim;Visual Studio Code,Notepad++;Vim;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows Subsystem for Linux (WSL),Doxygen;Jira;Obsidian,Jira,Jira,Discord;Microsoft Teams;Slack;Zoom,Discord;Microsoft Teams,Discord;Microsoft Teams,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,Showcase expertise with code solutions;Engage ...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,12.0,Strongly agree,Disagree,Neither agree nor disagree,Agree,Agree,Strongly disagree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Amount of technical debt;Complexity of tech st...,Knowledge sharing community,Hybrid (on-prem and cloud),A coworker,Software Development,0.0,0.0,30.0,30.0,0.0,0.0,20.0,10.0,10.0,Appropriate in length,Easy,NaN,8.0
14,"I used to be a developer by profession, but no...",35-44 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Stack Overflow;I...,API document(s) and/or SDK document(s);User gu...,20,NaN,Other (please specify):,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,PHP;Python,Python,Python,MariaDB;MySQL,NaN,NaN,NaN,NaN,NaN,CodeIgniter,NaN,NaN,CMake,NaN,NaN,NaN,NaN,NaN,Ant;APT,NaN,NaN,Visual Studio;Visual Studio Code,NaN,NaN,MacOS;Ubuntu;Windows;Windows Subsystem for Lin...,Ubuntu;Windows;Windows Subsystem for Linux (WSL),NaN,NaN,NaN,Discord,NaN,NaN,ChatGPT,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Highly trust,Very well at handling complex tasks,Learning about a codebase,NaN,NaN,Learning about a codebase,NaN,NaN,NaN,NaN,I'm not sure,Biased results that do not represent diverse v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65129,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,15,"Developer, full-stack",I don’t know,I have little or no influence,Start a free trial,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,Indonesia,IDR\tIndonesian rupiah,NaN,HTML/CSS;Java;JavaScript;PHP;Python;SQL,HTML/CSS;Java;JavaScript;PHP;SQL,HTML/CSS;Java;JavaScript;PHP;SQL,H2;Microsoft SQL Server;MySQL;PostgreSQL;SQLite,MySQL,MySQL,Amazon Web Services (AWS);Cloudflare;Digital O...,Amazon Web Services (AWS);Cloudflare;Digital O...,Amazon Web Services (AWS);Cloudflare;Digital O...,jQuery;React;Spring Boot,jQuery;Next.js;React;Spring Boot;Svelte,jQuery;React;Spring Boot,NaN,NaN,NaN,NaN,NaN,NaN,Composer;Docker;Maven (build tool);npm,Composer;npm;pnpm,Composer;npm,IntelliJ IDEA;Notepad++;PhpStorm,IntelliJ IDEA;Notepad++;PhpStorm,IntelliJ IDEA;Notepad++;PhpStorm,Fedora;Windows,Fedora;Windows,Confluence;Jira,Confluence;Jira,Confluence;Jira,Discord;Microsoft Teams;Whatsapp,Discord;Microsoft Teams;Whatsapp,Discord;Microsoft Teams;Whatsapp,Bing AI;ChatGPT;Google Gemini,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Quickly finding code solutions,"No, not at all",Yes,Favorable,Increase productivity;Greater efficiency,Neither trust nor distrust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Debugging and ge...,Committing and reviewing code;Deployment and m...,Learning about a codebase;Project planning;Pre...,NaN,NaN,Writing code;Documenting code;Debugging and ge...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65147,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Apples,Professional development or self-paced learnin...,"Secondary school (e.g. American high school, G...","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,10,"Developer, full-stack","10,000 or more employees",I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Quality support system;Repu...,Czech Republic,CZK\tCzech koruna,1690000.0,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,Bash/Shell (all shells);C#;HTML/CSS;PowerShell...,Bash/Shell (all shells);C#;HTML/CSS;PowerShell...,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,Microsoft Azure,Amazon Web Services (AWS);Microsoft Azure;Vercel,Microsoft Azure,ASP.NET;ASP.NET CORE;jQuery;Node.js;React,ASP.NET CORE;Deno;Next.js;Node.js;React,ASP.NET CORE;Node.js;React,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+),.NET (5+),Docker;Kubernetes;MSBuild;npm;NuGet;Vite;Webpack,Docker;Kubernetes;MSBuild;npm;NuGet;Vite;Webpack,Docker;Kubernetes;MSBuild;npm;NuGet;Vite;Webpack,Vim;Visual Studio;Visual Studio Code,Neovim;Rider;Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Azure Devops;Confluence;Jira;Markdown File,Azure Devops;Confluence;Markdown File;Notion;O...,Azure Devops;Confluence;Markdown File,Discord;Microsoft Teams;Slack;Zoom,Mattermost;Slack,Slack,GitHub Copilot;Visual Studio Intellicode,Codeium;GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Daily or almost daily,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, but I plan to soon",Indifferent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;Lack of prop...,Yes,Individual contributor,10.0,Strongly agree,Strongly agree,Disagree,Strongly disagree,Disagree,Agree,Neither agree nor disagree,Strongly disagree,Strongly disagree,1-2 times a week,3-5 times a week,10+ times a week,30-60 minutes a day,60-120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Hybrid (on-prem and cloud),Traditional public search engine,Manufacturing,30.0,0.0,5.0,35.0,0.0,20.0,10.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,8.0
65152,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,14,"Developer, back-end","5,000 to 9,999 employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,Estonia,EUR European Euro,90000.0,Groovy;Java;SQL,Java;JavaScript;Python;SQL;TypeScript,Java;SQL,MariaDB;MongoDB;PostgreSQL;Snowflake,MariaDB;MongoDB;PostgreSQL;Snowflake,MariaDB;MongoDB;PostgreSQL;Snowflake,Amazon Web Services (AWS),Amazon Web Services (AWS),Amazon Web Services (AWS),Spring Boot,React;Spring Boot,Spring Boot,NaN,NaN,NaN,Apache Kafka;Spring Framework,Apache Kafka;Spring Framework,Apache Kafka;Spring Framework,Docker;Gradle,Docker;Gradle,Docker;Gradle,DataGrip;IntelliJ IDEA;Visual Studio Code,DataGrip;IntelliJ IDEA;Visual Studio Code,DataGrip;IntelliJ IDEA;Visual Studio Code,iOS;iPadOS;MacOS,iOS;MacOS,Confluence;Jira;Lucid;Markdown File,Confluence;Jira;Lucid;Markdown File,Confluence;Jira;Lucid;Markdown File,Slack;Zoom,Slack;Zoom,Slack;Zoom,ChatGPT;GitHub Copilot;Perplexity AI,ChatGPT;Claude;GitHub Copilot;Google Gemini;Me...,ChatGPT;GitHub Copilot;Perplexity AI,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency,Somewhat distrust,Bad at handling complex tasks,Writing code;Generating content or synthetic data,Learning about a codebase;Project planning;Doc...,NaN,Writing code;Generating content or synthetic data,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,14.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Strongly agree,Disagree,Disagree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,30-60 minutes a day,Amount of technical debt,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),Slack search,Fintech,20.0,0.0,0.0,15.0,10.0,40.0,5.0,5.0,5.0,Appropriate in length,Easy,NaN,4.0
65253,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Contribute to open-source projects;Freelance/c...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,18,Other (please specify):,"10,000 or more employees",I have some influence,Visit developer communities like Stack Overflow,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Reputation...,United States of America,USD\tUnited States dollar,235000.0,Bash/Shell (all shells);C;C#;C++;Python;SQL;Ty...,Go;Rust,NaN,Cosmos DB;Microsoft SQL Server;SQLite,Clickhouse;Microsoft SQL Server;PostgreSQL;Sno...,Microsoft SQL Server,Amazon Web Services (AWS);Microsoft Azure,Amazon Web Services (AWS);Microsoft Azure,Amazon Web Services (AWS);Microsoft Azure,ASP.NET CORE;Blazor,ASP.NET CORE;Blazor;Svelte,ASP.NET CORE;Blazor,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+) ;.NET MAUI;CUDA;Tauri,.NET (5+),Docker;Visual Studio Solution,Podman;Unreal Engine;Visual Studio Solution;Vite,Visual Studio Solution,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Other Linux-based;Ubuntu;Windows;Windows Subsy...,Ubuntu;Windows;Windows Subsystem for Linux (WSL),Azure Devops,GitHub Discussions,NaN,Microsoft Teams,Microsoft Teams,Microsoft Teams,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,A few times per week,Not sure/can't remember,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
filt = df['LearnCode'].str.contains('Book')
df.loc[filt, 'LearnCode']

ResponseId
1                                   Books / Physical media
2        Books / Physical media;Colleague;On the job tr...
3        Books / Physical media;Colleague;On the job tr...
9        Books / Physical media;Other online resources ...
11       Books / Physical media;Other online resources ...
                               ...
65406    Books / Physical media;Colleague;On the job tr...
65412    Books / Physical media;On the job training;Oth...
65413    Books / Physical media;Online Courses or Certi...
65429    Books / Physical media;Colleague;Other online ...
65432    Books / Physical media;Colleague;On the job tr...
Name: LearnCode, Length: 30392, dtype: str